# Generated by Django 4.2.3 on 2024-09-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0014_marche_public_ouvert'),
    ]

    operations = [
        migrations.AddField(
            model_name='marche_public',
            name='heure_limite_delai',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
