# Generated by Django 4.2.3 on 2024-09-07 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0015_marche_public_heure_limite_delai'),
    ]

    operations = [
        migrations.AddField(
            model_name='marche_public',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrateur', to=settings.AUTH_USER_MODEL),
        ),
    ]
